apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: central-workflow
type: Opaque
stringData:
  # connection string: postgres://<user>:<password>@<service-name>:<port>/<db-name>
  DATABASE_URL: postgresql://postgres:supersecret@postgres-service:5432/workflow
  POSTGRES_PASSWORD: supersecret
