apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotion-app
  namespace: central-workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promotion-app
  template:
    metadata:
      labels:
        app: promotion-app
    spec:
      containers:
        - name: promotion-app
          image: promotion-app:latest
          imagePullPolicy: Never # use the local image
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
