apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-app
  namespace: central-workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-app
  template:
    metadata:
      labels:
        app: account-app
    spec:
      containers:
        - name: account-app
          image: account-app:latest
          imagePullPolicy: Never # use the local image
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
