apiVersion: v1
kind: Service
metadata:
  name: backend-workflow
  namespace: central-workflow
spec:
  type: NodePort
  selector:
    app: backend-workflow
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000
