apiVersion: v1
kind: Service
metadata:
  name: promotion-app
  namespace: central-workflow
spec:
  type: NodePort  
  selector:
    app: promotion-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003
