apiVersion: v1
kind: Service
metadata:
  name: host-app
  namespace: central-workflow
spec:
  type: NodePort  
  selector:
    app: host-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
