apiVersion: v1
kind: Service
metadata:
  name: account-app
  namespace: central-workflow
spec:
  type: NodePort  
  selector:
    app: account-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
